// ============================================================
// DOMAIN LAYER — ReviewResult
//
// The outcome of a completed review: the full list of comments
// that were generated by the LLM and posted to the PR.
//
// This is a simple value-holder ("output DTO" at domain level).
// In a production system you'd persist this so users could
// query past review results without re-running the LLM.
// ============================================================

namespace Domain.Entities;

public sealed class ReviewResult
{
    // Links this result back to the ReviewRequest that triggered it.
    public Guid ReviewRequestId { get; init; }

    // The actual feedback produced by the LLM.
    // Using IReadOnlyList instead of List signals that callers
    // should not mutate this collection after it is created.
    // The '= []' syntax (C# 12 collection expression) initializes
    // it to an empty list, preventing null reference issues.
    public IReadOnlyList<ReviewComment> Comments { get; init; } = [];

    // When the review was posted back to GitHub.
    public DateTimeOffset PostedAt { get; init; } = DateTimeOffset.UtcNow;
}
